function build_foc_ltid_blocks()
% BUILD_FOC_LTID_BLOCKS  atomic-block library for the foc-ltid method.
%
% Produces foc_ltid_blocks.slx (this method-local building_blocks/) (a Simulink Library) holding a
% SINGLE atom: KF_Estimator_EML — a generic discrete observer / Kalman-filter recursion
% (shared formula F6.a; reduces to a fixed-gain Luenberger observer, F4/F5, when fed a
% constant gain). The reference model's plant is an equation-based linear model and its
% dq transforms (Clark/Plark/Anti_Park) already live in the read-only base pmsm_blocks.slx,
% so they are reused BY POINTER and are NOT duplicated here.
%
% Discipline: NO numeric matrices, NO reference-specific values. A,B,C,D,Q,R
% enter as INPUT PORTS (wire Constant blocks sourced from InitFcn workspace variables);
% the block therefore carries zero numeric literals of its own. Layout is arbitrary and
% carries no topology hint. Idempotent: tears down any prior model/.slx first.

mdl  = 'foc_ltid_blocks';
here = fileparts(mfilename('fullpath'));
slx  = fullfile(here, [mdl '.slx']);

% ---- idempotent teardown ----
if bdIsLoaded(mdl); close_system(mdl, 0); end
if isfile(slx); delete(slx); end

% ---- new library ----
new_system(mdl, 'Library');
open_system(mdl);

% ---- KF_Estimator_EML atom ----
blk = [mdl '/KF_Estimator_EML'];
add_block('simulink/User-Defined Functions/MATLAB Function', blk);

code = strjoin({ ...
  'function [est_load, omega_hat, yhat] = KF_Estimator_EML(y, u, A, B, C, D, Q, R)' , ...
  '%#codegen' , ...
  '% Generic discrete observer / Kalman-filter recursion (shared formula F6.a).' , ...
  '% Reduces to a fixed-gain Luenberger observer (F4/F5) when driven by a constant gain.' , ...
  '% State convention (shared formula F2): x = [omega_m ; T_load], u = Te, y = omega_m.' , ...
  '% A,B,C,D,Q,R arrive as inputs (wire Constants sourced from InitFcn workspace vars);' , ...
  '% this atom holds NO numeric values of its own.' , ...
  'persistent xhat P' , ...
  'n = size(A,1);' , ...
  'if isempty(xhat)' , ...
  '    xhat = zeros(n,1);' , ...
  '    P    = eye(n);' , ...
  'end' , ...
  '% --- time update (predict) ---' , ...
  'xhat = A*xhat + B*u;' , ...
  'P    = A*P*A.'' + Q;' , ...
  '% --- measurement update (correct) ---' , ...
  'S     = C*P*C.'' + R;' , ...
  'K     = (P*C.'') / S;' , ...
  'resid = y - (C*xhat + D*u);' , ...
  'xhat  = xhat + K*resid;' , ...
  'P     = (eye(n) - K*C)*P;' , ...
  '% --- outputs ---' , ...
  'omega_hat = xhat(1);' , ...
  'est_load  = xhat(2);   % load-torque estimate (F2 state 2) -> F8 feed-forward' , ...
  'yhat      = C*xhat + D*u;' , ...
  'end' }, newline);

% proven R2024b idiom (see shared/building_blocks/api_notes.md §4, §11):
% a MATLAB Function block is backed by a Stateflow.EMChart; set its .Script and,
% for a persistent-state chart, inherit the sample time to avoid type deadlock.
ch = sfroot().find('-isa', 'Stateflow.EMChart', 'Path', blk);
ch.Script      = code;
ch.SampleTime  = '-1';
ch.ChartUpdate = 'INHERITED';

set_param(blk, 'Position', [100 100 280 240]);

% ---- save library ----
save_system(mdl, slx);
close_system(mdl, 0);
fprintf('Built %s\n', slx);
end
